version: '3'

services:
  app:
    container_name: prisma-auth-app
    build: 
      dockerfile: dockerfile
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file:
      - .env
    
